### ISSUE TITLE
directory organization

### ISSUE THREAD

**Issue by apreist14** [luckydesignlady/web-iv-portfolio-site#2]
Satisfactory
- the site folders are properly organized and labeled consistently but there are a few issues within the folder. You can get rid of the foundation.html also I think you can get rid of the robotos.txt and humans.txt to clear up your folder.

-the css folder should be placed within your styles folder
- in your images folder you have an illustrator file that should not be placed in there. 
  - your icons should be saved as svgs not pngs.

**Comment by e-m-durham** [comment]
Yep, make sure to clean up your directory of the unnecessary files.

It's fine to have the 'css' folder named 'css' since it is out-of-box foundation but it's important to keep the naming convention consistent so if you are going to go with 'css' and 'js' also use 'img' instead of 'images'

Yep, make sure you don't have source files in your images folder.

Make sure you are always placing hyphens-between-words.

You will want to make your icons .svg but that's more related to image optimization than directory organization.

**Comment by e-m-durham** [comment]
Scripts do need to be cleaned up to only what you are using, right now that's a lot of "code bloat" that's why you want to download the essentials or a custom foundation build.
